import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { createServer } from '../src/mcp/server.js';
import { JsonReceiptStore } from '../src/storage/jsonStore.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';

/**
 * A committed, synthetic store so the suite is reproducible on a fresh clone.
 * Resolved from `import.meta.dirname` rather than the process cwd, and
 * generated by importing `fixtures/sample.csv` through the real importer, so
 * it cannot drift from what the parser actually produces.
 */
const STORE = path.join(import.meta.dirname, 'fixtures', 'store.json');

/** Runs `body` against a connected client, closing both ends even if it throws. */
async function withClient(body: (client: Client) => Promise<void>): Promise<void> {
  const server = createServer(new JsonReceiptStore(STORE));
  const client = new Client({ name: 'test', version: '0.1' });
  const [ct, st] = InMemoryTransport.createLinkedPair();
  await Promise.all([server.connect(st), client.connect(ct)]);
  try {
    await body(client);
  } finally {
    await client.close();
    await server.close();
  }
}

async function callText(client: Client, name: string, args: Record<string, unknown> = {}): Promise<string> {
  const res = await client.callTool({ name, arguments: args });
  return (res.content as Array<{ type: string; text: string }>)[0]!.text;
}

describe('MCP server', () => {
  it('lists all 5 tools', async () => {
    await withClient(async (client) => {
      const { tools } = await client.listTools();
      const names = tools.map((t) => t.name).sort();
      assert.deepStrictEqual(names, ['get_receipt', 'get_spending', 'list_receipts', 'list_tags', 'split_costs']);
    });
  });

  it('list_receipts returns both receipts, newest first', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'list_receipts');
      assert.equal(
        text,
        [
          '2 receipt(s):',
          '',
          '2026-05-12  TESTMARKT (Wocheneinkauf)  -9.40 EUR  [4 items]  id:SAMPLEID000000000002',
          '2026-03-03  MUSTERMARKT  -17.06 EUR  [7 items]  id:SAMPLEID000000000001',
        ].join('\n'),
      );
    });
  });

  it('list_receipts filters by year and month', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'list_receipts', { year: 2026, month: 5 });
      assert.equal(
        text,
        [
          '1 receipt(s):',
          '',
          '2026-05-12  TESTMARKT (Wocheneinkauf)  -9.40 EUR  [4 items]  id:SAMPLEID000000000002',
        ].join('\n'),
      );
    });
  });

  it('get_receipt returns header and every line item with its tags', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'get_receipt', { receipt_id: 'SAMPLEID000000000001' });
      assert.equal(
        text,
        [
          'Date:    2026-03-03',
          'Store:   MUSTERMARKT',
          'Total:   -17.06 EUR',
          'Address: Beispielweg 12, 79100 Freiburg im Breisgau, Germany',
          'Payment: Karte (Visa)',
          '',
          'Items (7):',
          '  BIO BANANEN  -1.49 EUR  [gemeinsam]',
          '  VOLLKORNBROT  -2.79 EUR  [gemeinsam]',
          '  HAFERDRINK  -1.99 EUR  [Alice]',
          '  TOMATEN  -2.10 EUR  [Alice, Bob]',
          '  JOGHURT NATUR  -1.95 EUR  [Bob]',
          '  PFAND  0.25 EUR',
          '  KAFFEEBOHNEN  -6.99 EUR  [Alice]',
        ].join('\n'),
      );
    });
  });

  it('get_receipt reports an unknown id', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'get_receipt', { receipt_id: 'does-not-exist' });
      assert.equal(text, 'Receipt "does-not-exist" not found.');
    });
  });

  it('get_spending groups by month, newest first', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'get_spending');
      assert.equal(
        text,
        [
          'Spending by month:',
          '',
          '2026-05  -9.40 EUR  (1 receipts)',
          '2026-03  -17.06 EUR  (1 receipts)',
          '',
          'Total: -26.46 EUR',
        ].join('\n'),
      );
    });
  });

  it('list_tags counts how many items carry each tag', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'list_tags');
      assert.equal(text, ['Tags (3):', '', 'gemeinsam: 4', 'Alice: 4', 'Bob: 2'].join('\n'));
    });
  });

  it('split_costs divides shared items and lists what stayed unassigned', async () => {
    await withClient(async (client) => {
      const text = await callText(client, 'split_costs', {
        shared_tag: 'gemeinsam',
        participants: ['Alice', 'Bob'],
      });
      // TOMATEN is tagged with both participants, so it is split -1.05 each
      // rather than counted as shared. PFAND and BASILIKUM carry no tag at all;
      // they are listed in store order, which is newest receipt first.
      assert.equal(
        text,
        [
          'Shared total: -10.56 EUR (per person: -5.28 EUR)',
          '',
          'Alice: individual -11.52 EUR + shared -5.28 EUR = -16.80 EUR',
          'Bob: individual -3.00 EUR + shared -5.28 EUR = -8.28 EUR',
          '',
          '2 unassigned item(s):',
          '  BASILIKUM  -1.63 EUR',
          '  PFAND  0.25 EUR',
        ].join('\n'),
      );
    });
  });

  it('exposes the summary resource', async () => {
    await withClient(async (client) => {
      const { resources } = await client.listResources();
      assert.ok(resources.some((r) => r.uri === 'faircheck://receipts/summary'));

      const summary = await client.readResource({ uri: 'faircheck://receipts/summary' });
      const text = (summary.contents as Array<{ uri: string; text: string }>)[0]!.text;
      assert.equal(
        text,
        [
          'Faircheck data summary',
          'Receipts:   2',
          'Items:      11',
          'Period:     2026-03-03 – 2026-05-12',
          'Total:      -26.46 EUR',
          'Tags:       gemeinsam, Alice, Bob',
        ].join('\n'),
      );
    });
  });
});
